import { ConnectButton } from "@rainbow-me/rainbowkit";
//import { Button } from "../.next/components/button";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { useAccount } from "wagmi";
import styles from "../styles/Home.module.css";
// import PaymentRequest from "../components/RequestNetwork";
import { RequestLogicTypes } from '@requestnetwork/types';

//Diego's import
import React, {Fragment, useEffect} from 'react';
import Formulario from '../components/Formulario'
import Result from '../components/Result'
import axios from 'axios';



interface PaymentRequestProps {
	token: string | RequestLogicTypes.ICurrency,
	payerAddress: string,
	requestAmount: RequestLogicTypes.Amount
}
const Home: NextPage = () => {
  const [requestAmount, setRequestAmount] = useState('');
	const [paymentLink, setPaymentLink] = useState('');
  const { address } = useAccount(); 
  const [data, inputAI] = useState({}); //#1
  const [ result, setResultado ] = useState(false) //#2
  const handleCreateRequest = async () => {
		setRequestAmount('100');
    const request: PaymentRequestProps = {     
      token: 'USDT', 
      payerAddress: address || 'undefined',
      requestAmount: requestAmount
  }
		// const requestId = PaymentRequest(request);
		// setPaymentLink(`https://pay.request.network/${requestId}`);


	};
  //Diego's states*******************************************************************
    //defininr el state
    useEffect(()=> {
      
      if(Object.keys(data).length===0) return;

      // Function to make the POST request
      const postData = async () => {
          try {
          //  setResultado({})
            console.log('within the request')
        
            const response = await axios.get('http://localhost:8000/dummy_output');/*, {
              // Request body data
              user_address: '0x30c96825922151a293175993B74216D9FacDb668',
              contract_address: '0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413',
              audit:data */         

            console.log(response); // Response data from the server
           setResultado(response.data);
            const result = true;
          } catch (error) {
            console.error(error); // Handle error
          }
        };

        // Call the function to make the POST request
        postData();

    }, [data,data]);

  //  console.log(`there is response: ${response}`)

  return (
    <div className={styles.container}>
      <Head>
        <title>SC Auditors App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
      </Head>

      <main className={styles.main}> 
        <ConnectButton />

        <h1 className={styles.title}>Welcome to AI audit!</h1>

        
          <div className={styles.grid}>
          <a className={styles.card} href="https://rainbowkit.com">
            <h2>Create payment &rarr;</h2>
          </a>
        </div>
        <Fragment>
        <Formulario 
          inputAI={inputAI} 
        />
  
        </Fragment> 

        { (result) ? <Result 
                      result={result} />  
                    :null}

      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
