import React, { Fragment } from 'react';
import styles from "../styles/Home.module.css";
import Menu from '../components/Menu'
import Head from "next/head";
import { useState, useEffect } from "react";
import { useAccount } from "wagmi";
// import PaymentRequest from "../components/RequestNetwork";
import { RequestLogicTypes } from '@requestnetwork/types';

//Diego's import
import SimpleForm from '../components/SimpleForm'
//import { createBrowserRouter, RouterProvider } from 'react-router-dom'

import TwoFilesUpload from '../components/TwoFilesUpload'
import Switch from "@mui/material/Switch";
import FormControlLabel from "@mui/material/FormControlLabel";
//import Result from '../components/Result'
import aiResults from '../components/aiResults'
import { ConnectButton } from "@rainbow-me/rainbowkit";


import { MuiFileInput } from 'mui-file-input'

import { TextField } from '@mui/material'

//const [activateFileInput, setActivateFileInput] = useState(true);
//const [ airesults, setResultado ] = useState(false) //#2


let activateFileInput = null;
//let setResultado = null;
let address = null;
let result = null;
let setActivateFileInput = null;
let airesults = '';

const user = () => {
    const [myState, setMyState] = useState(null);
    useEffect(() => {
        if (typeof window !== 'undefined') {
          // Code that should only run on the client side
          setMyState('Initialized on the client side');
        }
      }, []);
    return (
        <div className={styles.container}>
      <Menu />
      <Head>
        <title>SC Auditors App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />


      </Head>

      <main className={styles.main}> 
        <ConnectButton />

        <h1 className={styles.title}>Welcome to AI audit!</h1>


        <div className={styles.grid}>
          <a className={styles.card} href="https://rainbowkit.com">
            <h2>Create payment &rarr;</h2>
          </a>
        </div>
        
        
        <Fragment>     
            <SimpleForm />
        </Fragment>

        <aiResults airesults={airesults} />  
    

      </main>
      <footer className={styles.footer}></footer>
    </div>
      );
}
 
export default user;