import { ConnectButton } from "@rainbow-me/rainbowkit";

import Head from "next/head";
import styles from "../styles/Home.module.css";
import Menu from '../components/Menu'

import React, { Fragment } from "react";

import { useState, useEffect } from "react";
import { useAccount } from "wagmi";

//Diego's import
import SimpleForm from '../components/SimpleForm'

//import Result from '../components/Result'
import AIResults from '../components/aiResults'



const user = () => {

  const [ textResult, setResultado ] = useState('');

    const [myState, setMyState] = useState(null);
    useEffect(() => {
        if (typeof window !== 'undefined') {
          // Code that should only run on the client side
          setMyState('Initialized on the client side');
        }
      }, []);
    return (
        <div className={styles.container}>
      <Menu />
      <Head>
        <title>SC Auditors App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />


      </Head>

      <main className={styles.main}> 
        <ConnectButton />

        <h1 className={styles.title}>Welcome to AI audit!</h1>
                
        <Fragment>     
            <SimpleForm resultFunction={setResultado} />
        </Fragment>

        <AIResults text_content={textResult} />  
    

      </main>
      <footer className={styles.footer}></footer>
    </div>
      );
}
 
export default user;